server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/hanu_hospital?createDatabaseIfNotExist=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Ho_Chi_Minh
    #url: jdbc:mysql://localhost:3306/hanu_hospital
    username: root
    password: freetoplay

    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

app:
  tokenSecret: HanuHospital180104
  tokenExpirationInMs: 864000000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG